### ISSUE TITLE
[BUG] 인수인계 전 Todo List

### ISSUE THREAD

**Issue by ILWAT** [JORDYMA-Link/Link-iOS#110]
### 제가 작성한 모든 코드를 인수인계 하기 전 해야할 작업 목록을 적어 놓는 Issue입니다.
- 이외에 추가적으로 진행해야하는 작업이 있다면 말씀해주시면 List 추가후 수정하겠습니다. 감사합니다.
- 이 이외에도 제가 작성한 코드에서 발생하는 추가 이슈는 인수인계 이후에도 책임 지도록 하겠습니다.

----------
- [x] Calendar 검색 Feed 관련 Update 관련 전체 구현(Menu->수정 && feed 클릭 -> 수정)
- [x] Calendar API 통신 직후 뷰 fscalendar update view code 안전성 향상
- [x] [외부 정책 문서 Common 모듈 이전](https://github.com/JORDYMA-Link/Link-iOS/pull/91#discussion_r1770666022)
- [x] Store Action/User Action Part 네이밍 변경 [ex) tappedButton(Prefix 형식) -> buttonTapped(Postfix 형식)]
- [ ] [@ViewBuilder로 작성한 View, Struct 이전 검토](https://github.com/JORDYMA-Link/Link-iOS/pull/50#issuecomment-2255924270)
- [x] 미사용 파일 및 주석, 디버깅 목적 로그 출력 코드 등 불필요한 코드 제거
- [ ] URL Validation 검증식 안정성 향상
----------
