### ISSUE TITLE
[FEATURE] 설정 구현

### ISSUE THREAD

**Issue by ILWAT** [JORDYMA-Link/Link-iOS#21]
## 💡 Issue

- 설정 구현

## 📝 Todo

- [ ]  설정 UI 구현
- [ ] 공지사항 UI 구현
- [ ] 탈퇴, 로그아웃, 닉네임 수정 동작 구현
