### ISSUE TITLE
[FEATURE] SettingView API 연결

### ISSUE THREAD

**Issue by ILWAT** [JORDYMA-Link/Link-iOS#62]
## 💡 Issue

- SettingView API 연결

## 📝 Todo

- [ ]  userProfile Get/Set
- [ ] 공지사항 View 구현
- [ ] 공지사항 Get/Set 구현
- [ ] 기타 Server 배포 API 연결
